### PR TITLE
Adds support for Vines mod

### PR DESCRIPTION
**Pull request by 6r1d**
Hello.
I think it's worth to add the support for [vines](https://github.com/bas080/vines) mod by @bas080. PR is tested locally, those vines work.
Thanks!

### CODE REVIEW

**Comment by OgelGames** [comment]
The vines don't need to be added to both the `biomass.convertible_groups` and `biomass.convertible_nodes`, just adding the group will cover them all.

**Comment by 6r1d** [comment]
> The vines don't need to be added to both the `biomass.convertible_groups` and `biomass.convertible_nodes`, just adding the group will cover them all.

Are you sure this is the case? If I remember correctly, adding a group only wasn't enough in tests yesterday.

**Comment by OgelGames** [comment]
> Are you sure this is the case?

Yes, groups `tree` and `leaves` work, don't they? :wink:

**Comment by 6r1d** [comment]
> Yes, groups `tree` and `leaves` work, don't they?

Yes. I did a test and removed all vines from `biomass.convertible_nodes`. There is a _currently unused_ node, `vines:vines`, which might become some kind of rope and it was not processed by the refinery, so I am leaving it for now.
It is outside the `vines` group, which initially motivated me to add all possible vines there.

**Comment by BuckarooBanzay** [comment]
@Lokrates ^

**Pull request merged**
